title: Jeonguk's blog
description: Jeonguk's blog
author: Jeonguk Lee
github: https://github.com/jeonguk
about: I am java developer.
disqus_shortname: jeonguk
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpeg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/dev_jeonguk"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/jeonguk"

share:
  twitter_username: jeonguk
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Blog Note
      url: /notes/
    - text: XML Feed
      url: /feed.xml

url: "https://jeonguk.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span: false
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-multiple-languages-plugin

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
